# Site settings
title: Euijae Kim
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Euijae Kim
user_description: Loves to build algorithms and systems that operate at scale. I am also passionate about image processing and solving complex problems in mathematical analysis.
user_title: Senior Software Engineer at Nike
email: euijae_kim@berkeley.edu
# twitter_username: lorem_ipsum
instagram_username: kim.euijae
facebook_username: 
linkedin_username: kimeuijae
github_username:  euijae
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

